apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
    <title>NFV Operations UI (Legacy)</title>
    <style>
      body { font-family: Roboto, sans-serif; background-color: #212121; color: #fff; display: flex; justify-content: center; align-items: center; height: 100vh; margin: 0; }
      h1 { font-size: 3rem; color: #4fc3f7; }
    </style>
    </head>
    <body>
      <div>
        <h1>Legacy NFV Ops Component</h1>
        <p>Awaiting Modernization.</p>
      </div>
    </body>
    </html>
