apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      hostNetwork: {{ .Values.security.hostNetwork }}
      hostPID: {{ .Values.security.hostPID }}
      containers:
        - name: nginx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
            - containerPort: 8080
              hostPort: 8080 
          securityContext:
            privileged: {{ .Values.security.privileged }}
            allowPrivilegeEscalation: {{ .Values.security.allowPrivilegeEscalation }}
          volumeMounts:
            - name: html-volume
              mountPath: /usr/share/nginx/html
            - name: host-var-log
              mountPath: /var/log/host-system
      volumes:
        - name: html-volume
          configMap:
            name: {{ .Release.Name }}-config
        - name: host-var-log
          hostPath:
            path: /var/log
            type: Directory
